##### Core / Prefix #####
set -g prefix C-a
unbind C-b
bind C-a send-prefix


##### Navigation / UI #####
set -g mouse on

bind -n WheelUpPane if -F '#{mouse_any_flag}' 'send-keys -M' 'copy-mode -e'
bind -n WheelDownPane select-pane -t= \; send-keys -M

unbind -n Tab
bind s choose-tree -s

set -g allow-rename off
set -g automatic-rename off


##### Plugins (TPM) #####
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-cpu'


##### Continuum / Resurrect #####
set -g @continuum-restore 'on'
set -g @continuum-save-interval '15'
# set -g @resurrect-capture-pane-contents 'on'


##### General #####
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",xterm-256color:RGB"
set -sg escape-time 0
set -g history-limit 100000


##### Everforest Minimal Polished #####
# bg        = #2d353b
# bg-alt    = #343f44
# bg-soft   = #3a464c
# border    = #4b565c
# fg        = #d3c6aa
# muted     = #859289
# green     = #a7c080
# aqua      = #83c092
# yellow    = #dbbc7f
# red       = #e67e80

set -g status-position bottom
set -g status-justify left
set -g status-style "bg=#2d353b,fg=#d3c6aa"
set -g status-left ""
set -g status-left-length 0
set -g status-right-length 100

set -g message-style "bg=#343f44,fg=#d3c6aa"
set -g message-command-style "bg=#a7c080,fg=#2d353b"

set -g pane-border-style "fg=#4b565c"
set -g pane-active-border-style "fg=#83c092"

set -g mode-style "bg=#a7c080,fg=#2d353b"


##### Tabs #####
set -g window-status-separator "  "

# inactive tabs
set -g window-status-format "#[fg=#859289,bg=#343f44]  #W  "

# active tab
set -g window-status-current-format "#[fg=#2d353b,bg=#d3c6aa,bold]  #W  "

set -g window-status-style "bg=#2d353b,fg=#859289"
set -g window-status-current-style "bg=#2d353b,fg=#d3c6aa"
set -g window-status-activity-style "fg=#dbbc7f,bg=#343f44"
set -g window-status-bell-style "fg=#2d353b,bg=#e67e80,bold"

setw -g monitor-activity on
set -g visual-activity off


##### Right #####
set -g status-right "#[fg=#a7c080]CPU #{cpu_percentage} #[fg=#859289]· #[fg=#dbbc7f]%H:%M "

##### Window switching (works in RU layout) #####
bind -T prefix n next-window
bind -T prefix т next-window
bind -T prefix p previous-window
bind -T prefix з previous-window


##### Splits keep current path #####
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"


##### Rename window #####
bind , command-prompt -I "#W" "rename-window '%%'"


##### Reload config #####
bind r source-file ~/.tmux.conf \; display-message "tmux.conf reloaded"


##### Popups #####
bind -r g display-popup -d "#{pane_current_path}" -w 85% -h 85% -E "zsh -lc 'lazygit'"
bind -r b display-popup -d "#{pane_current_path}" -w 85% -h 85% -E "zsh -lc 'btop'"


##### TPM init (MUST be last) #####
run '~/.tmux/plugins/tpm/tpm'
